In [1]:
def sequence1(n):
    return pow(n,2) + 2

import numpy as np

xVals = np.arange(0,5)

sequence1Array = sequence1(xVals)
print(list(sequence1Array))

[2, 3, 6, 11, 18]


In [2]:
def sequence2(n):
    return -1*pow(1/3,n-1)

print(sequence2(2))

-0.3333333333333333


In [3]:
x1Vals = sequence2(xVals)
print(x1Vals)

[-3.         -1.         -0.33333333 -0.11111111 -0.03703704]


Modeling the Sequence

[1,2,3,4]

$$ a_1 = 1 , r = 1 $$
$$ a_n = n $$

In [6]:
def sequence3(n):
    return 5 + 3*(n-1)

sequence3Array = sequence3(xVals)
print(sequence3Array)

thirteenthTerm = sequence3(13)
print(thirteenthTerm)



[ 2  5  8 11 14]
41


In [7]:
pow(7,3)

343

$$ \sum_{n=1}^{6}{\frac{n}{2n + 1}} $$ 

In [8]:
xVals = np.arange(1,7)

def series1(n):
    return n / (2*n + 1)

numbers = series1(xVals)

print(numbers)

[0.33333333 0.4        0.42857143 0.44444444 0.45454545 0.46153846]


In [9]:
def series2(n):
    return 3*n + 1
newXVals = np.arange(1,13)
numbers2 = series2(newXVals)
print(sum(numbers2))

246


In [10]:
3 + 9 + 27 + 81

120

$$ \sum_{n=1}^{6}{-4*(\frac{1}{2})^{n-1}} $$ 

In [11]:
def series3(n):
    a1 = -4 
    return a1*pow(0.5,n-1)

numbers3 = series3(xVals)
print(numbers3)

[-4.    -2.    -1.    -0.5   -0.25  -0.125]


In [12]:
sum(numbers3)

-7.875

In [13]:
-63 / 8

-7.875

The sum of first three terms in a finite geometric series is $ \frac{-7}{10} $ Their product is $ \frac{-1}{125} $ 

$$ \sum_{n=1}^{3}{a_1 * (r)^{n-1}} = \frac{-7}{10} $$ 

$$ a_1 + a_2 + a_3 = \frac{-7}{10} $$ 

$$ r = \frac{a_2}{a_1} when n = 2 and \frac{a_3}{a_2} when n = 3 $$ 

$$ a_1 * a_2 * a_3  = \frac{-1}{125} $$ 

$$ a_3 = a_1 * \frac{\frac{-1}{125*a_1*a_2}}{a_2} $$ 