In [3]:
import numpy as np 

s1 = np.array([2,7,-38])
s2 = np.array([-5,-8,38])

newSystem = 5*s1 + 2*s2
print(newSystem)

[   0   19 -114]


$$ 19y = -114 $$ 

$$ y = \frac{-114}{19} $$ 

In [4]:
-114 / 19 

-6.0

In [5]:
p1 = np.array([1,-5,-8])
p2 = np.array([2,-4,-3])

print(p1 - p2)

[-1 -1 -5]


$$ \frac{6x^4 - 2x^3 - 13x - 7}{3x + 8} $$ 

In [6]:
polynomial = np.array([6,-2,0,-13,-7])
factor = np.array([3,8])

print(np.polydiv(polynomial,factor))

(array([  2.,  -6.,  16., -47.]), array([369.]))


In [8]:
from numpy import convolve

f1 = np.array([3,9])
f2 = np.array([1,3])
f3 = np.array([8,12])

product1 = convolve(f1,f2)

summation = product1 + 2*f3 

print(summation)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 