In [3]:
import numpy as np 

s1 = np.array([2,7,-38])
s2 = np.array([-5,-8,38])

newSystem = 5*s1 + 2*s2
print(newSystem)

[   0   19 -114]


$$ 19y = -114 $$ 

$$ y = \frac{-114}{19} $$ 

In [4]:
-114 / 19 

-6.0

In [5]:
p1 = np.array([1,-5,-8])
p2 = np.array([2,-4,-3])

print(p1 - p2)

[-1 -1 -5]


$$ \frac{6x^4 - 2x^3 - 13x - 7}{3x + 8} $$ 

In [6]:
polynomial = np.array([6,-2,0,-13,-7])
factor = np.array([3,8])

print(np.polydiv(polynomial,factor))

(array([  2.,  -6.,  16., -47.]), array([369.]))


In [9]:
from numpy import convolve

f1 = np.array([3,9])
f2 = np.array([1,3])
f3 = np.array([0,8,12])

product1 = convolve(f1,f2)

summation = product1 + 2*f3 

print(summation)

[ 3 34 51]


In [11]:
yF1 = np.array([0,1,4])
yF2 = np.array([1,-2])
yF3 = np.array([3,0,10])

equation = 3*yF1 + convolve(yF2, np.array([2,0]))
print(equation)

[ 2 -1 12]


In [15]:
yF4 = np.array([3,0,10])
difference = yF4 - equation

print(np.roots(difference))


[-2.  1.]


$$ 2y^2 -y + 12 = 3y^2 + 10 $$ 

$$ 0 = y^2 + y - 2 $$  

In [16]:
f5 = np.array([1,2,-1])
print(np.roots(f5))

[-2.41421356  0.41421356]


In [19]:
import math as m
-1 + m.sqrt(2)

0.41421356237309515

In [22]:
def distance(p1: np.array, p2: np.array):
    return m.sqrt(((pow(p2[0],2)) - pow(p1[0],2)) + ((pow(p2[1],2)) - (pow(p1[1],2)))) 

In [23]:
print(distance(np.array([-3,4]), np.array([8,-7])))

9.38083151964686


In [24]:
m.sqrt(242)

15.556349186104045

In [25]:
11 * 11 

121

In [26]:
121 + 121 

242

In [27]:
2 + 3*37

113

In [28]:
2 + 3*36

110

In [30]:
import math as m
def permutation(n,r):
       return m.factorial(n) / m.factorial(n-r)

print(permutation(10,7))

604800.0


In [31]:
12 + 16 + 15

43

In [32]:
12 * 16  

192

In [33]:
43 * 42 

1806

In [34]:
192 / 1806

0.10631229235880399

In [35]:
32 / 301

0.10631229235880399